language: cpp

jobs:
  include:
    - os: linux
      env: PYTHON_VERSION="3.7.9" COMPILER="gcc" GCCv="9" BENCHMARK=1
    - os: linux
      env: PYTHON_VERSION="3.7.9" COMPILER="gcc" GCCv="7" TEST_SERIAL=1
    - os: linux
      env: PYTHON_VERSION="3.6.9" COMPILER="gcc" GCCv="6"
      if: branch = master
    - os: linux
      env: PYTHON_VERSION="3.7.9" COMPILER="gcc" GCCv="8"
      if: branch = master

before_install:
  - export GXX="g++-$GCCv" GCC="gcc-$GCCv"
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-get -q update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install $GXX
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/$GXX 0
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/$GCC 0
  - g++ --version
  - gcc --version
  - wget "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install -y python=$PYTHON_VERSION
  - echo $PYTHON_VERSION
  - conda install -y cmake -c anaconda
  - conda install -y -c conda-forge tbb-devel xsimd xtensor xtensor-blas numpy xtensor-python
  - export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
  - if [[ "$TEST_SERIAL" == 1 ]]; then export BUILD_SERIAL_FOAM=1; fi
  - pip install -e .[test]

script:
  - python setup.py build_ext --inplace --with-tests
  - python setup.py test -v
  - if [[ "$BENCHMARK" == 1 ]]; then python setup.py benchmark -v; fi