trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    clang9:
      LLVM_VERSION: '9.0'
    clang5:
      LLVM_VERSION: '5.0'

variables:
  CC: clang-$(LLVM_VERSION)
  CXX: clang++-$(LLVM_VERSION)

steps:
  - checkout: self

  - script: |
      sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      sudo apt-get update
      sudo apt-get --no-install-suggests --no-install-recommends install $CXX
    displayName: "Install build toolchain"

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: "Add conda to PATH"

  - script: |
      conda create --yes --quiet --name foamalgo
      source activate foamalgo
      conda install -y cmake -c anaconda
      conda install -y -c conda-forge tbb-devel xsimd xtensor xtensor-blas numpy xtensor-python
    displayName: "Create Anaconda environment"

  - script: |
      source activate foamalgo
      export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
      pip install -e .[test]
      python setup.py build_ext --inplace --with-tests
      python setup.py test -v
    displayName: 'Build and test'
